### ISSUE TITLE
Test issue for AB#6696

### ISSUE THREAD

**Issue by Saibamen** [gandalan/idas-client-libs#439]
Test issue for [AB#6696](https://dev.azure.com/gandalan/a6dd0e1c-ebfd-41aa-9f9d-b1a04a1e3bc1/_workitems/edit/6696)

**Comment by gdl-reif** [comment]
Another test: AB#6696

**Comment by Saibamen** [comment]
[AB#6696](https://dev.azure.com/gandalan/a6dd0e1c-ebfd-41aa-9f9d-b1a04a1e3bc1/_workitems/edit/6696)
